[tool.poetry]
name = "biopython-playground"
version = "0.1.0"
description = ""
authors = ["Anna Julia Engel <anna.julia.engel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
biopython = "^1.79"

[tool.poetry.dev-dependencies]
ipython = "7.34"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
